-- =============================================
-- Seed: Expanded US Assets (Stocks, ETFs, REITs)
-- =============================================

-- US Stocks - Large Cap (S&P 500 top companies)
INSERT INTO public.invest_assets (ticker, name, asset_type, currency, exchange) VALUES
  -- Tech
  ('AAPL', 'Apple Inc', 'us_stock', 'USD', 'NASDAQ'),
  ('MSFT', 'Microsoft Corp', 'us_stock', 'USD', 'NASDAQ'),
  ('GOOGL', 'Alphabet Inc Class A', 'us_stock', 'USD', 'NASDAQ'),
  ('GOOG', 'Alphabet Inc Class C', 'us_stock', 'USD', 'NASDAQ'),
  ('AMZN', 'Amazon.com Inc', 'us_stock', 'USD', 'NASDAQ'),
  ('NVDA', 'NVIDIA Corp', 'us_stock', 'USD', 'NASDAQ'),
  ('TSLA', 'Tesla Inc', 'us_stock', 'USD', 'NASDAQ'),
  ('META', 'Meta Platforms Inc', 'us_stock', 'USD', 'NASDAQ'),
  ('AVGO', 'Broadcom Inc', 'us_stock', 'USD', 'NASDAQ'),
  ('ORCL', 'Oracle Corp', 'us_stock', 'USD', 'NYSE'),
  ('CRM', 'Salesforce Inc', 'us_stock', 'USD', 'NYSE'),
  ('AMD', 'Advanced Micro Devices', 'us_stock', 'USD', 'NASDAQ'),
  ('ADBE', 'Adobe Inc', 'us_stock', 'USD', 'NASDAQ'),
  ('INTC', 'Intel Corp', 'us_stock', 'USD', 'NASDAQ'),
  ('CSCO', 'Cisco Systems', 'us_stock', 'USD', 'NASDAQ'),
  ('QCOM', 'Qualcomm Inc', 'us_stock', 'USD', 'NASDAQ'),
  ('TXN', 'Texas Instruments', 'us_stock', 'USD', 'NASDAQ'),
  ('INTU', 'Intuit Inc', 'us_stock', 'USD', 'NASDAQ'),
  ('AMAT', 'Applied Materials', 'us_stock', 'USD', 'NASDAQ'),
  ('MU', 'Micron Technology', 'us_stock', 'USD', 'NASDAQ'),
  ('LRCX', 'Lam Research', 'us_stock', 'USD', 'NASDAQ'),
  ('KLAC', 'KLA Corp', 'us_stock', 'USD', 'NASDAQ'),
  ('SNPS', 'Synopsys Inc', 'us_stock', 'USD', 'NASDAQ'),
  ('CDNS', 'Cadence Design Systems', 'us_stock', 'USD', 'NASDAQ'),
  ('NFLX', 'Netflix Inc', 'us_stock', 'USD', 'NASDAQ'),
  ('PLTR', 'Palantir Technologies', 'us_stock', 'USD', 'NYSE'),
  ('NOW', 'ServiceNow Inc', 'us_stock', 'USD', 'NYSE'),
  ('UBER', 'Uber Technologies', 'us_stock', 'USD', 'NYSE'),
  ('SHOP', 'Shopify Inc', 'us_stock', 'USD', 'NYSE'),
  ('SQ', 'Block Inc', 'us_stock', 'USD', 'NYSE'),
  ('SNOW', 'Snowflake Inc', 'us_stock', 'USD', 'NYSE'),
  ('NET', 'Cloudflare Inc', 'us_stock', 'USD', 'NYSE'),
  ('CRWD', 'CrowdStrike Holdings', 'us_stock', 'USD', 'NASDAQ'),
  ('PANW', 'Palo Alto Networks', 'us_stock', 'USD', 'NASDAQ'),
  ('DDOG', 'Datadog Inc', 'us_stock', 'USD', 'NASDAQ'),
  ('ZS', 'Zscaler Inc', 'us_stock', 'USD', 'NASDAQ'),
  ('MSTR', 'MicroStrategy Inc', 'us_stock', 'USD', 'NASDAQ'),
  ('ARM', 'Arm Holdings', 'us_stock', 'USD', 'NASDAQ'),
  -- Finance
  ('JPM', 'JPMorgan Chase', 'us_stock', 'USD', 'NYSE'),
  ('V', 'Visa Inc', 'us_stock', 'USD', 'NYSE'),
  ('MA', 'Mastercard Inc', 'us_stock', 'USD', 'NYSE'),
  ('BAC', 'Bank of America', 'us_stock', 'USD', 'NYSE'),
  ('WFC', 'Wells Fargo', 'us_stock', 'USD', 'NYSE'),
  ('GS', 'Goldman Sachs', 'us_stock', 'USD', 'NYSE'),
  ('MS', 'Morgan Stanley', 'us_stock', 'USD', 'NYSE'),
  ('BLK', 'BlackRock Inc', 'us_stock', 'USD', 'NYSE'),
  ('SCHW', 'Charles Schwab', 'us_stock', 'USD', 'NYSE'),
  ('C', 'Citigroup Inc', 'us_stock', 'USD', 'NYSE'),
  ('AXP', 'American Express', 'us_stock', 'USD', 'NYSE'),
  ('PYPL', 'PayPal Holdings', 'us_stock', 'USD', 'NASDAQ'),
  ('COIN', 'Coinbase Global', 'us_stock', 'USD', 'NASDAQ'),
  ('HOOD', 'Robinhood Markets', 'us_stock', 'USD', 'NASDAQ'),
  ('SOFI', 'SoFi Technologies', 'us_stock', 'USD', 'NASDAQ'),
  -- Healthcare
  ('UNH', 'UnitedHealth Group', 'us_stock', 'USD', 'NYSE'),
  ('JNJ', 'Johnson & Johnson', 'us_stock', 'USD', 'NYSE'),
  ('LLY', 'Eli Lilly', 'us_stock', 'USD', 'NYSE'),
  ('ABBV', 'AbbVie Inc', 'us_stock', 'USD', 'NYSE'),
  ('MRK', 'Merck & Co', 'us_stock', 'USD', 'NYSE'),
  ('PFE', 'Pfizer Inc', 'us_stock', 'USD', 'NYSE'),
  ('TMO', 'Thermo Fisher Scientific', 'us_stock', 'USD', 'NYSE'),
  ('ABT', 'Abbott Laboratories', 'us_stock', 'USD', 'NYSE'),
  ('DHR', 'Danaher Corp', 'us_stock', 'USD', 'NYSE'),
  ('BMY', 'Bristol-Myers Squibb', 'us_stock', 'USD', 'NYSE'),
  ('AMGN', 'Amgen Inc', 'us_stock', 'USD', 'NASDAQ'),
  ('GILD', 'Gilead Sciences', 'us_stock', 'USD', 'NASDAQ'),
  ('ISRG', 'Intuitive Surgical', 'us_stock', 'USD', 'NASDAQ'),
  ('MRNA', 'Moderna Inc', 'us_stock', 'USD', 'NASDAQ'),
  -- Consumer
  ('KO', 'Coca-Cola Co', 'us_stock', 'USD', 'NYSE'),
  ('PEP', 'PepsiCo Inc', 'us_stock', 'USD', 'NASDAQ'),
  ('PG', 'Procter & Gamble', 'us_stock', 'USD', 'NYSE'),
  ('COST', 'Costco Wholesale', 'us_stock', 'USD', 'NASDAQ'),
  ('WMT', 'Walmart Inc', 'us_stock', 'USD', 'NYSE'),
  ('NKE', 'Nike Inc', 'us_stock', 'USD', 'NYSE'),
  ('MCD', 'McDonalds Corp', 'us_stock', 'USD', 'NYSE'),
  ('SBUX', 'Starbucks Corp', 'us_stock', 'USD', 'NASDAQ'),
  ('DIS', 'Walt Disney Co', 'us_stock', 'USD', 'NYSE'),
  ('HD', 'Home Depot', 'us_stock', 'USD', 'NYSE'),
  ('LOW', 'Lowes Companies', 'us_stock', 'USD', 'NYSE'),
  ('TGT', 'Target Corp', 'us_stock', 'USD', 'NYSE'),
  ('ABNB', 'Airbnb Inc', 'us_stock', 'USD', 'NASDAQ'),
  ('BKNG', 'Booking Holdings', 'us_stock', 'USD', 'NASDAQ'),
  -- Industrial / Energy
  ('XOM', 'Exxon Mobil', 'us_stock', 'USD', 'NYSE'),
  ('CVX', 'Chevron Corp', 'us_stock', 'USD', 'NYSE'),
  ('COP', 'ConocoPhillips', 'us_stock', 'USD', 'NYSE'),
  ('BA', 'Boeing Co', 'us_stock', 'USD', 'NYSE'),
  ('CAT', 'Caterpillar Inc', 'us_stock', 'USD', 'NYSE'),
  ('GE', 'GE Aerospace', 'us_stock', 'USD', 'NYSE'),
  ('RTX', 'RTX Corp', 'us_stock', 'USD', 'NYSE'),
  ('LMT', 'Lockheed Martin', 'us_stock', 'USD', 'NYSE'),
  ('HON', 'Honeywell Intl', 'us_stock', 'USD', 'NASDAQ'),
  ('UPS', 'United Parcel Service', 'us_stock', 'USD', 'NYSE'),
  ('DE', 'Deere & Co', 'us_stock', 'USD', 'NYSE'),
  ('NEE', 'NextEra Energy', 'us_stock', 'USD', 'NYSE'),
  -- Telecom / Media
  ('T', 'AT&T Inc', 'us_stock', 'USD', 'NYSE'),
  ('VZ', 'Verizon Communications', 'us_stock', 'USD', 'NYSE'),
  ('TMUS', 'T-Mobile US', 'us_stock', 'USD', 'NASDAQ'),
  ('CMCSA', 'Comcast Corp', 'us_stock', 'USD', 'NASDAQ'),
  -- Other notable
  ('BRK.B', 'Berkshire Hathaway B', 'us_stock', 'USD', 'NYSE'),
  ('LIN', 'Linde plc', 'us_stock', 'USD', 'NASDAQ'),
  ('UNP', 'Union Pacific', 'us_stock', 'USD', 'NYSE'),
  ('SPGI', 'S&P Global', 'us_stock', 'USD', 'NYSE'),
  ('ADP', 'Automatic Data Processing', 'us_stock', 'USD', 'NASDAQ'),
  ('MMM', '3M Company', 'us_stock', 'USD', 'NYSE'),
  ('IBM', 'IBM Corp', 'us_stock', 'USD', 'NYSE'),
  ('GEV', 'GE Vernova', 'us_stock', 'USD', 'NYSE')
ON CONFLICT (ticker) DO NOTHING;

-- US ETFs - Popular
INSERT INTO public.invest_assets (ticker, name, asset_type, currency, exchange) VALUES
  -- Index ETFs
  ('VOO', 'Vanguard S&P 500 ETF', 'us_etf', 'USD', 'NYSE'),
  ('SPY', 'SPDR S&P 500 ETF', 'us_etf', 'USD', 'NYSE'),
  ('IVV', 'iShares Core S&P 500 ETF', 'us_etf', 'USD', 'NYSE'),
  ('QQQ', 'Invesco QQQ Trust', 'us_etf', 'USD', 'NASDAQ'),
  ('VTI', 'Vanguard Total Stock Market ETF', 'us_etf', 'USD', 'NYSE'),
  ('DIA', 'SPDR Dow Jones Industrial ETF', 'us_etf', 'USD', 'NYSE'),
  ('IWM', 'iShares Russell 2000 ETF', 'us_etf', 'USD', 'NYSE'),
  ('VUG', 'Vanguard Growth ETF', 'us_etf', 'USD', 'NYSE'),
  ('VTV', 'Vanguard Value ETF', 'us_etf', 'USD', 'NYSE'),
  ('RSP', 'Invesco S&P 500 Equal Weight', 'us_etf', 'USD', 'NYSE'),
  -- Dividend ETFs
  ('SCHD', 'Schwab US Dividend Equity ETF', 'us_etf', 'USD', 'NYSE'),
  ('VYM', 'Vanguard High Dividend Yield ETF', 'us_etf', 'USD', 'NYSE'),
  ('DVY', 'iShares Select Dividend ETF', 'us_etf', 'USD', 'NASDAQ'),
  ('HDV', 'iShares Core High Dividend ETF', 'us_etf', 'USD', 'NYSE'),
  ('JEPI', 'JPMorgan Equity Premium Income ETF', 'us_etf', 'USD', 'NYSE'),
  ('JEPQ', 'JPMorgan Nasdaq Equity Premium Income', 'us_etf', 'USD', 'NASDAQ'),
  -- International ETFs
  ('VEA', 'Vanguard FTSE Developed Markets ETF', 'us_etf', 'USD', 'NYSE'),
  ('VWO', 'Vanguard FTSE Emerging Markets ETF', 'us_etf', 'USD', 'NYSE'),
  ('VXUS', 'Vanguard Total Intl Stock ETF', 'us_etf', 'USD', 'NASDAQ'),
  ('EWZ', 'iShares MSCI Brazil ETF', 'us_etf', 'USD', 'NYSE'),
  ('EEM', 'iShares MSCI Emerging Markets ETF', 'us_etf', 'USD', 'NYSE'),
  ('IEMG', 'iShares Core MSCI EM ETF', 'us_etf', 'USD', 'NYSE'),
  -- Bond ETFs
  ('BND', 'Vanguard Total Bond Market ETF', 'us_etf', 'USD', 'NASDAQ'),
  ('AGG', 'iShares Core US Aggregate Bond ETF', 'us_etf', 'USD', 'NYSE'),
  ('TLT', 'iShares 20+ Year Treasury Bond ETF', 'us_etf', 'USD', 'NASDAQ'),
  ('SHY', 'iShares 1-3 Year Treasury Bond ETF', 'us_etf', 'USD', 'NASDAQ'),
  ('VCIT', 'Vanguard Interm Corp Bond ETF', 'us_etf', 'USD', 'NASDAQ'),
  ('LQD', 'iShares iBoxx Investment Grade Corp', 'us_etf', 'USD', 'NYSE'),
  ('HYG', 'iShares iBoxx High Yield Corp Bond', 'us_etf', 'USD', 'NYSE'),
  ('TIPS', 'iShares TIPS Bond ETF', 'us_etf', 'USD', 'NYSE'),
  -- Sector ETFs
  ('XLK', 'Technology Select Sector SPDR', 'us_etf', 'USD', 'NYSE'),
  ('XLF', 'Financial Select Sector SPDR', 'us_etf', 'USD', 'NYSE'),
  ('XLV', 'Health Care Select Sector SPDR', 'us_etf', 'USD', 'NYSE'),
  ('XLE', 'Energy Select Sector SPDR', 'us_etf', 'USD', 'NYSE'),
  ('XLI', 'Industrial Select Sector SPDR', 'us_etf', 'USD', 'NYSE'),
  ('XLP', 'Consumer Staples Select Sector SPDR', 'us_etf', 'USD', 'NYSE'),
  ('XLY', 'Consumer Discretionary Select SPDR', 'us_etf', 'USD', 'NYSE'),
  ('XLU', 'Utilities Select Sector SPDR', 'us_etf', 'USD', 'NYSE'),
  ('XLRE', 'Real Estate Select Sector SPDR', 'us_etf', 'USD', 'NYSE'),
  -- Commodity / Gold ETFs
  ('GLD', 'SPDR Gold Shares', 'us_etf', 'USD', 'NYSE'),
  ('IAU', 'iShares Gold Trust', 'us_etf', 'USD', 'NYSE'),
  ('SLV', 'iShares Silver Trust', 'us_etf', 'USD', 'NYSE'),
  ('USO', 'United States Oil Fund', 'us_etf', 'USD', 'NYSE'),
  -- Crypto ETFs
  ('IBIT', 'iShares Bitcoin Trust ETF', 'us_etf', 'USD', 'NASDAQ'),
  ('FBTC', 'Fidelity Wise Origin Bitcoin Fund', 'us_etf', 'USD', 'NYSE'),
  ('ETHA', 'iShares Ethereum Trust ETF', 'us_etf', 'USD', 'NASDAQ'),
  -- Thematic ETFs
  ('ARKK', 'ARK Innovation ETF', 'us_etf', 'USD', 'NYSE'),
  ('SOXX', 'iShares Semiconductor ETF', 'us_etf', 'USD', 'NASDAQ'),
  ('SMH', 'VanEck Semiconductor ETF', 'us_etf', 'USD', 'NASDAQ'),
  ('KWEB', 'KraneShares CSI China Internet ETF', 'us_etf', 'USD', 'NYSE')
ON CONFLICT (ticker) DO NOTHING;

-- US REITs
INSERT INTO public.invest_assets (ticker, name, asset_type, currency, exchange) VALUES
  ('O', 'Realty Income Corp', 'us_stock', 'USD', 'NYSE'),
  ('AMT', 'American Tower Corp', 'us_stock', 'USD', 'NYSE'),
  ('PLD', 'Prologis Inc', 'us_stock', 'USD', 'NYSE'),
  ('CCI', 'Crown Castle Intl', 'us_stock', 'USD', 'NYSE'),
  ('EQIX', 'Equinix Inc', 'us_stock', 'USD', 'NASDAQ'),
  ('SPG', 'Simon Property Group', 'us_stock', 'USD', 'NYSE'),
  ('DLR', 'Digital Realty Trust', 'us_stock', 'USD', 'NYSE'),
  ('PSA', 'Public Storage', 'us_stock', 'USD', 'NYSE'),
  ('WELL', 'Welltower Inc', 'us_stock', 'USD', 'NYSE'),
  ('AVB', 'AvalonBay Communities', 'us_stock', 'USD', 'NYSE'),
  ('EQR', 'Equity Residential', 'us_stock', 'USD', 'NYSE'),
  ('VTR', 'Ventas Inc', 'us_stock', 'USD', 'NYSE'),
  ('ARE', 'Alexandria Real Estate', 'us_stock', 'USD', 'NYSE'),
  ('MAA', 'Mid-America Apartment', 'us_stock', 'USD', 'NYSE'),
  ('STAG', 'STAG Industrial', 'us_stock', 'USD', 'NYSE'),
  ('NNN', 'NNN REIT Inc', 'us_stock', 'USD', 'NYSE'),
  ('VICI', 'VICI Properties', 'us_stock', 'USD', 'NYSE'),
  ('IRM', 'Iron Mountain Inc', 'us_stock', 'USD', 'NYSE'),
  -- REIT ETFs
  ('VNQ', 'Vanguard Real Estate ETF', 'us_etf', 'USD', 'NYSE'),
  ('SCHH', 'Schwab US REIT ETF', 'us_etf', 'USD', 'NYSE')
ON CONFLICT (ticker) DO NOTHING;

-- Additional Crypto (popular ones not yet seeded)
INSERT INTO public.invest_assets (ticker, name, asset_type, currency, exchange, coingecko_id) VALUES
  ('DOGE', 'Dogecoin', 'crypto', 'USD', 'CoinGecko', 'dogecoin'),
  ('SHIB', 'Shiba Inu', 'crypto', 'USD', 'CoinGecko', 'shiba-inu'),
  ('TRX', 'TRON', 'crypto', 'USD', 'CoinGecko', 'tron'),
  ('TON', 'Toncoin', 'crypto', 'USD', 'CoinGecko', 'the-open-network'),
  ('SUI', 'Sui', 'crypto', 'USD', 'CoinGecko', 'sui'),
  ('APT', 'Aptos', 'crypto', 'USD', 'CoinGecko', 'aptos'),
  ('NEAR', 'NEAR Protocol', 'crypto', 'USD', 'CoinGecko', 'near'),
  ('UNI', 'Uniswap', 'crypto', 'USD', 'CoinGecko', 'uniswap'),
  ('AAVE', 'Aave', 'crypto', 'USD', 'CoinGecko', 'aave'),
  ('LTC', 'Litecoin', 'crypto', 'USD', 'CoinGecko', 'litecoin'),
  ('BCH', 'Bitcoin Cash', 'crypto', 'USD', 'CoinGecko', 'bitcoin-cash'),
  ('FIL', 'Filecoin', 'crypto', 'USD', 'CoinGecko', 'filecoin'),
  ('ATOM', 'Cosmos', 'crypto', 'USD', 'CoinGecko', 'cosmos'),
  ('ARB', 'Arbitrum', 'crypto', 'USD', 'CoinGecko', 'arbitrum'),
  ('OP', 'Optimism', 'crypto', 'USD', 'CoinGecko', 'optimism'),
  ('INJ', 'Injective', 'crypto', 'USD', 'CoinGecko', 'injective-protocol'),
  ('RENDER', 'Render Token', 'crypto', 'USD', 'CoinGecko', 'render-token'),
  ('FET', 'Fetch.ai', 'crypto', 'USD', 'CoinGecko', 'fetch-ai'),
  ('PEPE', 'Pepe', 'crypto', 'USD', 'CoinGecko', 'pepe'),
  ('WIF', 'dogwifhat', 'crypto', 'USD', 'CoinGecko', 'dogwifcoin')
ON CONFLICT (ticker) DO NOTHING;
