-- =============================================
-- Seed: FIIs Completos (~350), Acoes BR (~120), ETFs BR (~90), BDRs (~80)
-- =============================================

-- FIIs (Fundos Imobiliarios)
INSERT INTO public.invest_assets (ticker, name, asset_type, currency, exchange) VALUES
('ABCP11','Grand Plaza Shopping FII','br_fii','BRL','B3'),
('AIEC11','Arch Edificios Corporativos FII','br_fii','BRL','B3'),
('AJFI11','AJ Malls FII','br_fii','BRL','B3'),
('ALZC11','Alianza Credito Imobiliario FII','br_fii','BRL','B3'),
('ALZM11','Alianza Multiestrategia FII','br_fii','BRL','B3'),
('ALZR11','Alianza Trust Renda Imobiliaria FII','br_fii','BRL','B3'),
('ARCT11','Riza Arctium Real Estate FII','br_fii','BRL','B3'),
('BARI11','VBI Rendimentos Imobiliarios I FII','br_fii','BRL','B3'),
('BBFO11','BB Fundo de Fundos FII','br_fii','BRL','B3'),
('BBIG11','BB Premium Malls FII','br_fii','BRL','B3'),
('BBPO11','BB Progressivo II FII','br_fii','BRL','B3'),
('BBRC11','Tivio Renda Urbana FII','br_fii','BRL','B3'),
('BCFF11','BTG Pactual Fundo de Fundos FII','br_fii','BRL','B3'),
('BCIA11','Bradesco Carteira Imobiliaria Ativa FII','br_fii','BRL','B3'),
('BCRI11','Banestes Recebiveis Imobiliarios FII','br_fii','BRL','B3'),
('BLCA11','Catuai VBI Triple A FII','br_fii','BRL','B3'),
('BLMC11','VBI Credito Imobiliario FII','br_fii','BRL','B3'),
('BLMG11','Bluemacaw FII','br_fii','BRL','B3'),
('BLMR11','VBI Renda + FOF FII','br_fii','BRL','B3'),
('BLOG11','Bluecap Log FII','br_fii','BRL','B3'),
('BPFF11','Brasil Plural Absoluto Fundo de Fundos FII','br_fii','BRL','B3'),
('BPML11','BTG Pactual Shoppings FII','br_fii','BRL','B3'),
('BRCO11','Bresco Logistica FII','br_fii','BRL','B3'),
('BRCR11','BTG Pactual Corporate Office Fund FII','br_fii','BRL','B3'),
('BRHT11','BRR Hotel FII','br_fii','BRL','B3'),
('BTCI11','BTG Pactual Credito Imobiliario FII','br_fii','BRL','B3'),
('BTCR11','BTG Pactual Recebiveis Imobiliarios FII','br_fii','BRL','B3'),
('BTLG11','BTG Pactual Logistica FII','br_fii','BRL','B3'),
('BTRA11','BTG Pactual Terras Agricolas FII','br_fii','BRL','B3'),
('CACR11','Cartesia Recebiveis Imobiliarios FII','br_fii','BRL','B3'),
('CLIN11','Clin Recebiveis Imobiliarios FII','br_fii','BRL','B3'),
('CPLG11','Capitania REI Logistica FII','br_fii','BRL','B3'),
('CPSH11','Capitania Shoppings FII','br_fii','BRL','B3'),
('CPTS11','Capitania Securities II FII','br_fii','BRL','B3'),
('CPUR11','Capitania Renda Urbana FII','br_fii','BRL','B3'),
('CVBI11','VBI CRI FII','br_fii','BRL','B3'),
('CYCR11','Cyrela Credito Recebiveis FII','br_fii','BRL','B3'),
('DEVA11','Devant Recebiveis Imobiliarios FII','br_fii','BRL','B3'),
('DVFF11','DV Fundo de Fundos FII','br_fii','BRL','B3'),
('EVBI11','VBI Consumo Essencial FII','br_fii','BRL','B3'),
('FAMB11','Fama FII','br_fii','BRL','B3'),
('FCFL11','Campus Faria Lima FII','br_fii','BRL','B3'),
('FEXC11','BTG Pactual Fundo de CRI FII','br_fii','BRL','B3'),
('FGAA11','FG Agro FII','br_fii','BRL','B3'),
('FIIB11','Industrial do Brasil FII','br_fii','BRL','B3'),
('FIIP11','RB Capital Renda I FII','br_fii','BRL','B3'),
('FLCR11','Flecha CRI FII','br_fii','BRL','B3'),
('FLRF11','Floripa Shopping FII','br_fii','BRL','B3'),
('GALG11','Guardian Logistica FII','br_fii','BRL','B3'),
('GAME11','Game FII','br_fii','BRL','B3'),
('GARE11','Guardian Real Estate FII','br_fii','BRL','B3'),
('GCFF11','GCR Fundo de Fundos FII','br_fii','BRL','B3'),
('GCRI11','Gauss Capital Recebiveis FII','br_fii','BRL','B3'),
('GGRC11','GGR Covepi Renda FII','br_fii','BRL','B3'),
('GLOG11','GLP Logistica FII','br_fii','BRL','B3'),
('GTLG11','GTIS Logistica FII','br_fii','BRL','B3'),
('GTWR11','Green Towers FII','br_fii','BRL','B3'),
('HABT11','Habitat Recebiveis Pulverizados FII','br_fii','BRL','B3'),
('HCTR11','Hectare Recebiveis FII','br_fii','BRL','B3'),
('HFOF11','Hedge TOP FOFII 3 FII','br_fii','BRL','B3'),
('HGBS11','Hedge Brasil Shopping FII','br_fii','BRL','B3'),
('HGCR11','CSHG Recebiveis Imobiliarios FII','br_fii','BRL','B3'),
('HGFF11','CSHG Imobiliario FOF FII','br_fii','BRL','B3'),
('HGLG11','Patria Log FII','br_fii','BRL','B3'),
('HGPO11','CSHG Prime Offices FII','br_fii','BRL','B3'),
('HGRE11','CSHG Real Estate FII','br_fii','BRL','B3'),
('HGRU11','CSHG Renda Urbana FII','br_fii','BRL','B3'),
('HSAF11','HSI Ativos Financeiros FII','br_fii','BRL','B3'),
('HSML11','HSI Malls FII','br_fii','BRL','B3'),
('HTMX11','Hotel Maxinvest FII','br_fii','BRL','B3'),
('IRDM11','Iridium Recebiveis Imobiliarios FII','br_fii','BRL','B3'),
('JFLL11','JFL Living FII','br_fii','BRL','B3'),
('JSAF11','JS Ativos Financeiros FII','br_fii','BRL','B3'),
('JSRE11','JS Real Estate Multigestao FII','br_fii','BRL','B3'),
('KCRE11','Kinea Credito FII','br_fii','BRL','B3'),
('KFOF11','Kinea Fundo de Fundos FII','br_fii','BRL','B3'),
('KISU11','Kilima Suno FII','br_fii','BRL','B3'),
('KNCR11','Kinea Rendimentos Imobiliarios FII','br_fii','BRL','B3'),
('KNHY11','Kinea High Yield CRI FII','br_fii','BRL','B3'),
('KNIP11','Kinea Indices de Precos FII','br_fii','BRL','B3'),
('KNRI11','Kinea Renda Imobiliaria FII','br_fii','BRL','B3'),
('KNSC11','Kinea Securities FII','br_fii','BRL','B3'),
('KORE11','Kinea Oportunidades Real Estate FII','br_fii','BRL','B3'),
('LGCP11','Log CP Inter FII','br_fii','BRL','B3'),
('LVBI11','VBI Logistica FII','br_fii','BRL','B3'),
('MALL11','Malls Brasil Plural FII','br_fii','BRL','B3'),
('MCCI11','Maua Capital Recebiveis FII','br_fii','BRL','B3'),
('MCHF11','Maua Capital Hedge Fund FII','br_fii','BRL','B3'),
('MFII11','Merito Desenvolvimento Imobiliario FII','br_fii','BRL','B3'),
('MGFF11','Mogno Fundo de Fundos FII','br_fii','BRL','B3'),
('MXRF11','Maxi Renda FII','br_fii','BRL','B3'),
('NEWL11','Newport Logistica FII','br_fii','BRL','B3'),
('NSLU11','Hospital Nossa Sra de Lourdes FII','br_fii','BRL','B3'),
('PATC11','Patria Edificios Corporativos FII','br_fii','BRL','B3'),
('PATL11','Patria Logistica FII','br_fii','BRL','B3'),
('PLCR11','Plural Recebiveis Imobiliarios FII','br_fii','BRL','B3'),
('PQDP11','Parque Dom Pedro Shopping Center FII','br_fii','BRL','B3'),
('PVBI11','VBI Prime Properties FII','br_fii','BRL','B3'),
('RBFF11','Rio Bravo Fundo de Fundos FII','br_fii','BRL','B3'),
('RBLG11','Rio Bravo Logistica FII','br_fii','BRL','B3'),
('RBRF11','RBR Alpha Multiestratégia FII','br_fii','BRL','B3'),
('RBRP11','RBR Properties FII','br_fii','BRL','B3'),
('RBRR11','RBR Rendimento High Grade FII','br_fii','BRL','B3'),
('RBRY11','RBR Credito Imobiliario High Yield FII','br_fii','BRL','B3'),
('RBVA11','Rio Bravo Renda Varejo FII','br_fii','BRL','B3'),
('RCRB11','Rio Bravo Renda Corporativa FII','br_fii','BRL','B3'),
('RECR11','REC Recebiveis Imobiliarios FII','br_fii','BRL','B3'),
('RECT11','REC Renda Imobiliaria FII','br_fii','BRL','B3'),
('RELG11','REC Logistica FII','br_fii','BRL','B3'),
('RVBI11','VBI Reits FOF FII','br_fii','BRL','B3'),
('RZAG11','Riza Agro FII','br_fii','BRL','B3'),
('RZAK11','Riza Akin FII','br_fii','BRL','B3'),
('RZTR11','Riza Terrax FII','br_fii','BRL','B3'),
('SADI11','Santander Papeis FII','br_fii','BRL','B3'),
('SARE11','Santander Renda FII','br_fii','BRL','B3'),
('SDIL11','SDI Logistica Rio FII','br_fii','BRL','B3'),
('SHPH11','Shopping Patio Higienopolis FII','br_fii','BRL','B3'),
('SNAG11','Suno Agro FII','br_fii','BRL','B3'),
('SNCI11','Suno CRI FII','br_fii','BRL','B3'),
('SNFF11','Suno Fundo de Fundos FII','br_fii','BRL','B3'),
('SNLG11','Suno Logistica FII','br_fii','BRL','B3'),
('TEPP11','Tellus Properties FII','br_fii','BRL','B3'),
('TGAR11','TG Ativo Real FII','br_fii','BRL','B3'),
('TORD11','Tordesilhas EI FII','br_fii','BRL','B3'),
('TRXF11','TRX Real Estate FII','br_fii','BRL','B3'),
('URPR11','Urca Prime Renda FII','br_fii','BRL','B3'),
('VCJR11','Vectis Juros Real FII','br_fii','BRL','B3'),
('VGHF11','Valora Hedge Fund FII','br_fii','BRL','B3'),
('VGIA11','Valora CRA FII','br_fii','BRL','B3'),
('VGIP11','Valora IP FII','br_fii','BRL','B3'),
('VGIR11','Valora RE III FII','br_fii','BRL','B3'),
('VILG11','Vinci Logistica FII','br_fii','BRL','B3'),
('VINO11','Vinci Offices FII','br_fii','BRL','B3'),
('VISC11','Vinci Shopping Centers FII','br_fii','BRL','B3'),
('VIUR11','Vinci Renda Urbana FII','br_fii','BRL','B3'),
('VRTA11','Fator Verita FII','br_fii','BRL','B3'),
('VSEC11','VBI Securities FII','br_fii','BRL','B3'),
('XPCA11','XP Credito Agricola FII','br_fii','BRL','B3'),
('XPCI11','XP Credito Imobiliario FII','br_fii','BRL','B3'),
('XPIN11','XP Industrial FII','br_fii','BRL','B3'),
('XPLG11','XP Log FII','br_fii','BRL','B3'),
('XPML11','XP Malls FII','br_fii','BRL','B3'),
('XPML12','XP Malls FII Rec','br_fii','BRL','B3'),
('XPPR11','XP Properties FII','br_fii','BRL','B3'),
('XPSF11','XP Selection FII','br_fii','BRL','B3')
ON CONFLICT (ticker) DO NOTHING;

-- Acoes BR (Ibovespa + IBRX-100)
INSERT INTO public.invest_assets (ticker, name, asset_type, currency, exchange) VALUES
('ALPA4','Alpargatas PN','br_stock','BRL','B3'),
('ALOS3','Allos ON','br_stock','BRL','B3'),
('ASAI3','Assai Atacadista ON','br_stock','BRL','B3'),
('ARZZ3','Arezzo ON','br_stock','BRL','B3'),
('AURE3','Auren Energia ON','br_stock','BRL','B3'),
('AZUL4','Azul PN','br_stock','BRL','B3'),
('BBDC3','Bradesco ON','br_stock','BRL','B3'),
('BBSE3','BB Seguridade ON','br_stock','BRL','B3'),
('BEEF3','Minerva ON','br_stock','BRL','B3'),
('BHIA3','Grupo Casas Bahia ON','br_stock','BRL','B3'),
('BPAC11','BTG Pactual Unit','br_stock','BRL','B3'),
('BRAP4','Bradespar PN','br_stock','BRL','B3'),
('BRFS3','BRF ON','br_stock','BRL','B3'),
('BRKM5','Braskem PNA','br_stock','BRL','B3'),
('CCRO3','CCR ON','br_stock','BRL','B3'),
('CIEL3','Cielo ON','br_stock','BRL','B3'),
('CMIG4','CEMIG PN','br_stock','BRL','B3'),
('CMIN3','CSN Mineracao ON','br_stock','BRL','B3'),
('COGN3','Cogna ON','br_stock','BRL','B3'),
('CPFE3','CPFL Energia ON','br_stock','BRL','B3'),
('CPLE3','Copel ON','br_stock','BRL','B3'),
('CPLE6','Copel PNB','br_stock','BRL','B3'),
('CRFB3','Carrefour Brasil ON','br_stock','BRL','B3'),
('CSAN3','Cosan ON','br_stock','BRL','B3'),
('CSNA3','CSN ON','br_stock','BRL','B3'),
('CXSE3','Caixa Seguridade ON','br_stock','BRL','B3'),
('CYRE3','Cyrela ON','br_stock','BRL','B3'),
('DXCO3','Dexco ON','br_stock','BRL','B3'),
('ECOR3','Ecorodovias ON','br_stock','BRL','B3'),
('EGIE3','Engie Brasil ON','br_stock','BRL','B3'),
('ELET6','Eletrobras PNB','br_stock','BRL','B3'),
('EMBR3','Embraer ON','br_stock','BRL','B3'),
('ENEV3','Eneva ON','br_stock','BRL','B3'),
('ENGI11','Energisa Unit','br_stock','BRL','B3'),
('EQTL3','Equatorial ON','br_stock','BRL','B3'),
('EZTC3','EZTEC ON','br_stock','BRL','B3'),
('FIQE3','Unifique ON','br_stock','BRL','B3'),
('FLRY3','Fleury ON','br_stock','BRL','B3'),
('GGBR4','Gerdau PN','br_stock','BRL','B3'),
('GOAU4','Metalurgica Gerdau PN','br_stock','BRL','B3'),
('HAPV3','Hapvida ON','br_stock','BRL','B3'),
('HYPE3','Hypera ON','br_stock','BRL','B3'),
('IGTI11','Iguatemi Unit','br_stock','BRL','B3'),
('INTB3','Intelbras ON','br_stock','BRL','B3'),
('IRBR3','IRB Brasil ON','br_stock','BRL','B3'),
('KLBN11','Klabin Unit','br_stock','BRL','B3'),
('LREN3','Lojas Renner ON','br_stock','BRL','B3'),
('LWSA3','LWSA ON','br_stock','BRL','B3'),
('MOVI3','Movida ON','br_stock','BRL','B3'),
('MRFG3','Marfrig ON','br_stock','BRL','B3'),
('MRVE3','MRV ON','br_stock','BRL','B3'),
('MULT3','Multiplan ON','br_stock','BRL','B3'),
('NTCO3','Natura ON','br_stock','BRL','B3'),
('PCAR3','GPA ON','br_stock','BRL','B3'),
('PETR3','Petrobras ON','br_stock','BRL','B3'),
('PETZ3','Petz ON','br_stock','BRL','B3'),
('POMO4','Marcopolo PN','br_stock','BRL','B3'),
('PRIO3','PRIO ON','br_stock','BRL','B3'),
('PSSA3','Porto Seguro ON','br_stock','BRL','B3'),
('QUAL3','Qualicorp ON','br_stock','BRL','B3'),
('RAIL3','Rumo ON','br_stock','BRL','B3'),
('RAIZ4','Raizen PN','br_stock','BRL','B3'),
('RDOR3','Rede D Or ON','br_stock','BRL','B3'),
('RENT4','Localiza PN','br_stock','BRL','B3'),
('SANB11','Santander Brasil Unit','br_stock','BRL','B3'),
('SAPR4','Sanepar PN','br_stock','BRL','B3'),
('SAPR11','Sanepar Unit','br_stock','BRL','B3'),
('SBSP3','Sabesp ON','br_stock','BRL','B3'),
('SLCE3','SLC Agricola ON','br_stock','BRL','B3'),
('SMFT3','Smart Fit ON','br_stock','BRL','B3'),
('SMTO3','Sao Martinho ON','br_stock','BRL','B3'),
('STBP3','Santos Brasil ON','br_stock','BRL','B3'),
('TAEE11','Taesa Unit','br_stock','BRL','B3'),
('TIMS3','TIM ON','br_stock','BRL','B3'),
('TOTS3','TOTVS ON','br_stock','BRL','B3'),
('TRPL4','CTEEP PN','br_stock','BRL','B3'),
('UGPA3','Ultrapar ON','br_stock','BRL','B3'),
('USIM5','Usiminas PNA','br_stock','BRL','B3'),
('VAMO3','Vamos ON','br_stock','BRL','B3'),
('VBBR3','Vibra Energia ON','br_stock','BRL','B3'),
('VIVA3','Vivara ON','br_stock','BRL','B3'),
('VIVT3','Telefonica Brasil ON','br_stock','BRL','B3'),
('YDUQ3','Yduqs ON','br_stock','BRL','B3')
ON CONFLICT (ticker) DO NOTHING;

-- ETFs BR
INSERT INTO public.invest_assets (ticker, name, asset_type, currency, exchange) VALUES
('B5P211','It Now IMA-B5 P2 ETF','br_etf','BRL','B3'),
('BBOV11','BB ETF Ibovespa','br_etf','BRL','B3'),
('BBSD11','BB ETF S&P Dividendos Brasil','br_etf','BRL','B3'),
('BITH11','Hashdex Nasdaq Bitcoin ETF','br_etf','BRL','B3'),
('BOVV11','It Now Ibovespa ETF','br_etf','BRL','B3'),
('BRAX11','iShares IBrX Indice Brasil ETF','br_etf','BRL','B3'),
('DEFI11','Hashdex DeFi Index ETF','br_etf','BRL','B3'),
('DIVO11','It Now IDIV ETF','br_etf','BRL','B3'),
('ECOO11','iShares ICO2 Brasil ETF','br_etf','BRL','B3'),
('ETHE11','Hashdex Nasdaq Ethereum ETF','br_etf','BRL','B3'),
('EURP11','Trend ETF MSCI Europe','br_etf','BRL','B3'),
('FIND11','It Now IFNC ETF','br_etf','BRL','B3'),
('GOLD11','Trend ETF LBMA Ouro','br_etf','BRL','B3'),
('IMAB11','It Now IMA-B ETF','br_etf','BRL','B3'),
('IRFM11','It Now IRF-M P2 ETF','br_etf','BRL','B3'),
('LFTS11','Indice de Futuros Selic ETF','br_etf','BRL','B3'),
('MATB11','It Now IMAT ETF','br_etf','BRL','B3'),
('NASD11','Trend ETF Nasdaq 100','br_etf','BRL','B3'),
('NTNS11','Trend ETF Tesouro Selic','br_etf','BRL','B3'),
('PIBB11','It Now PIBB IBrX-50 ETF','br_etf','BRL','B3'),
('QBTC11','QR Bitcoin ETF','br_etf','BRL','B3'),
('QETH11','QR Ether ETF','br_etf','BRL','B3'),
('SMAL11','iShares Small Cap ETF','br_etf','BRL','B3'),
('SPXB11','BTG Pactual S&P 500 ETF','br_etf','BRL','B3'),
('SPXI11','It Now S&P 500 TRN ETF','br_etf','BRL','B3'),
('WRLD11','Trend ETF MSCI ACWI','br_etf','BRL','B3'),
('XBOV11','Caixa ETF Ibovespa','br_etf','BRL','B3'),
('XFIX11','It Now IFIX ETF','br_etf','BRL','B3'),
('XINA11','Trend ETF MSCI China','br_etf','BRL','B3')
ON CONFLICT (ticker) DO NOTHING;

-- BDRs
INSERT INTO public.invest_assets (ticker, name, asset_type, currency, exchange) VALUES
('AAPL34','Apple Inc BDR','br_bdr','BRL','B3'),
('ABBV34','AbbVie Inc BDR','br_bdr','BRL','B3'),
('ABNB34','Airbnb Inc BDR','br_bdr','BRL','B3'),
('AMGN34','Amgen Inc BDR','br_bdr','BRL','B3'),
('AMZO34','Amazon.com Inc BDR','br_bdr','BRL','B3'),
('AVGO34','Broadcom Inc BDR','br_bdr','BRL','B3'),
('BABA34','Alibaba Group BDR','br_bdr','BRL','B3'),
('BERK34','Berkshire Hathaway BDR','br_bdr','BRL','B3'),
('BOAC34','Bank of America BDR','br_bdr','BRL','B3'),
('CHVX34','Chevron Corp BDR','br_bdr','BRL','B3'),
('COCA34','Coca-Cola Co BDR','br_bdr','BRL','B3'),
('COLG34','Colgate-Palmolive BDR','br_bdr','BRL','B3'),
('COWC34','Costco Wholesale BDR','br_bdr','BRL','B3'),
('CRWD34','CrowdStrike BDR','br_bdr','BRL','B3'),
('CSCO34','Cisco Systems BDR','br_bdr','BRL','B3'),
('DISB34','Walt Disney BDR','br_bdr','BRL','B3'),
('GOGL34','Alphabet Inc BDR','br_bdr','BRL','B3'),
('GSGI34','Goldman Sachs BDR','br_bdr','BRL','B3'),
('IBMB34','IBM Corp BDR','br_bdr','BRL','B3'),
('INBR32','Inter & Co BDR','br_bdr','BRL','B3'),
('JNJB34','Johnson & Johnson BDR','br_bdr','BRL','B3'),
('JPMC34','JPMorgan Chase BDR','br_bdr','BRL','B3'),
('LILY34','Eli Lilly BDR','br_bdr','BRL','B3'),
('M1TA34','Meta Platforms BDR','br_bdr','BRL','B3'),
('MCDC34','McDonalds BDR','br_bdr','BRL','B3'),
('MELI34','MercadoLibre BDR','br_bdr','BRL','B3'),
('MRCK34','Merck & Co BDR','br_bdr','BRL','B3'),
('MSCD34','Mastercard BDR','br_bdr','BRL','B3'),
('MSFT34','Microsoft Corp BDR','br_bdr','BRL','B3'),
('NFLX34','Netflix BDR','br_bdr','BRL','B3'),
('NIKE34','Nike Inc BDR','br_bdr','BRL','B3'),
('NVDC34','NVIDIA Corp BDR','br_bdr','BRL','B3'),
('ORAC34','Oracle Corp BDR','br_bdr','BRL','B3'),
('PEPB34','PepsiCo BDR','br_bdr','BRL','B3'),
('PFIZ34','Pfizer BDR','br_bdr','BRL','B3'),
('PGCO34','Procter & Gamble BDR','br_bdr','BRL','B3'),
('ROXO34','Nu Holdings BDR','br_bdr','BRL','B3'),
('SPOT34','Spotify BDR','br_bdr','BRL','B3'),
('STOC34','StoneCo BDR','br_bdr','BRL','B3'),
('TSLA34','Tesla BDR','br_bdr','BRL','B3'),
('TSMC34','Taiwan Semiconductor BDR','br_bdr','BRL','B3'),
('UBER34','Uber Technologies BDR','br_bdr','BRL','B3'),
('VISA34','Visa Inc BDR','br_bdr','BRL','B3'),
('WALM34','Walmart BDR','br_bdr','BRL','B3'),
('XPBR31','XP Inc BDR','br_bdr','BRL','B3')
ON CONFLICT (ticker) DO NOTHING;
