-- =============================================
-- Seed: Comprehensive asset expansion
-- BR Stocks (Small/Mid Caps), US Stocks, REITs, Fixed Income, Debentures
-- =============================================

-- BR Stocks (Small/Mid Caps not in previous seeds)
INSERT INTO public.invest_assets (ticker, name, asset_type, currency, exchange) VALUES
('AALR3','Alliar ON','br_stock','BRL','B3'),
('ABCB4','ABC Brasil PN','br_stock','BRL','B3'),
('AGRO3','BrasilAgro ON','br_stock','BRL','B3'),
('AGXY3','Agrogalaxy ON','br_stock','BRL','B3'),
('ALLD3','Allied ON','br_stock','BRL','B3'),
('ALSO3','Aliansce Sonae ON','br_stock','BRL','B3'),
('ALUP11','Alupar Unit','br_stock','BRL','B3'),
('AMBP3','Ambipar ON','br_stock','BRL','B3'),
('ANIM3','Anima ON','br_stock','BRL','B3'),
('ARML3','Armac ON','br_stock','BRL','B3'),
('ATMP3','Atmos Energia ON','br_stock','BRL','B3'),
('AURA33','Aura Minerals BDR','br_stock','BRL','B3'),
('BEES3','Banestes ON','br_stock','BRL','B3'),
('BEES4','Banestes PN','br_stock','BRL','B3'),
('BLAU3','Blau Farmaceutica ON','br_stock','BRL','B3'),
('BMGB4','BMG PN','br_stock','BRL','B3'),
('BMOB3','Bemobi ON','br_stock','BRL','B3'),
('BOAS3','Boa Safra ON','br_stock','BRL','B3'),
('BOBR4','Bombril PN','br_stock','BRL','B3'),
('BPAN4','Banco Pan PN','br_stock','BRL','B3'),
('BRBI11','BR Advisory Unit','br_stock','BRL','B3'),
('BRIT3','Brisanet ON','br_stock','BRL','B3'),
('BRSR6','Banrisul PNB','br_stock','BRL','B3'),
('CAML3','Camil ON','br_stock','BRL','B3'),
('CASH3','Meliuz ON','br_stock','BRL','B3'),
('CBAV3','CBA ON','br_stock','BRL','B3'),
('CEAB3','CEA Modas ON','br_stock','BRL','B3'),
('CLSA3','Clearsale ON','br_stock','BRL','B3'),
('CMIG3','CEMIG ON','br_stock','BRL','B3'),
('COCE5','Coelce PNA','br_stock','BRL','B3'),
('CSMG3','COPASA ON','br_stock','BRL','B3'),
('CSUD3','CSU Digital ON','br_stock','BRL','B3'),
('CURY3','Cury ON','br_stock','BRL','B3'),
('DESK3','Desktop ON','br_stock','BRL','B3'),
('DIRR3','Direcional ON','br_stock','BRL','B3'),
('DMVF3','Dimed ON','br_stock','BRL','B3'),
('ELMD3','Eletromidia ON','br_stock','BRL','B3'),
('ENBR3','Energias do Brasil ON','br_stock','BRL','B3'),
('ESPA3','Espacolaser ON','br_stock','BRL','B3'),
('EVEN3','Even ON','br_stock','BRL','B3'),
('FESA4','Ferbasa PN','br_stock','BRL','B3'),
('FRAS3','Fras-le ON','br_stock','BRL','B3'),
('GFSA3','Gafisa ON','br_stock','BRL','B3'),
('GMAT3','Grupo Mateus ON','br_stock','BRL','B3'),
('GRND3','Grendene ON','br_stock','BRL','B3'),
('GUAR3','Guararapes ON','br_stock','BRL','B3'),
('HBSA3','Hidrovias do Brasil ON','br_stock','BRL','B3'),
('IFCM3','Infracommerce ON','br_stock','BRL','B3'),
('ITUB3','Itau Unibanco ON','br_stock','BRL','B3'),
('JALL3','Jalles Machado ON','br_stock','BRL','B3'),
('JHSF3','JHSF ON','br_stock','BRL','B3'),
('KEPL3','Kepler Weber ON','br_stock','BRL','B3'),
('LAVV3','Lavvi ON','br_stock','BRL','B3'),
('LEVE3','Mahle Metal Leve ON','br_stock','BRL','B3'),
('LJQQ3','Quero-Quero ON','br_stock','BRL','B3'),
('LOGG3','LOG Commercial ON','br_stock','BRL','B3'),
('MATD3','Mater Dei ON','br_stock','BRL','B3'),
('MBLY3','Mobly ON','br_stock','BRL','B3'),
('MDNE3','Moura Dubeux ON','br_stock','BRL','B3'),
('MEGA3','Omega Energia ON','br_stock','BRL','B3'),
('MILS3','Mills ON','br_stock','BRL','B3'),
('MLAS3','Multilaser ON','br_stock','BRL','B3'),
('MTRE3','Mitre Realty ON','br_stock','BRL','B3'),
('NEOE3','Neoenergia ON','br_stock','BRL','B3'),
('NGRD3','Neogrid ON','br_stock','BRL','B3'),
('NTCO3','Natura ON','br_stock','BRL','B3'),
('ODPV3','Odontoprev ON','br_stock','BRL','B3'),
('ONCO3','Oncoclinicas ON','br_stock','BRL','B3'),
('OPCT3','Oceanpact ON','br_stock','BRL','B3'),
('ORVR3','Orizon ON','br_stock','BRL','B3'),
('PETZ3','Petz ON','br_stock','BRL','B3'),
('PGMN3','Pague Menos ON','br_stock','BRL','B3'),
('PLPL3','Plano & Plano ON','br_stock','BRL','B3'),
('PMAM3','Paranapanema ON','br_stock','BRL','B3'),
('PORT3','Wilson Sons ON','br_stock','BRL','B3'),
('POSI3','Positivo ON','br_stock','BRL','B3'),
('PTBL3','PBG ON','br_stock','BRL','B3'),
('RAPT4','Randon PN','br_stock','BRL','B3'),
('RCSL4','Recrusul PN','br_stock','BRL','B3'),
('RECV3','PetroReconcavo ON','br_stock','BRL','B3'),
('REDE3','Rede Energia ON','br_stock','BRL','B3'),
('ROMI3','Romi ON','br_stock','BRL','B3'),
('RRRP3','3R Petroleum ON','br_stock','BRL','B3'),
('RSID3','Rossi ON','br_stock','BRL','B3'),
('SEER3','Ser Educacional ON','br_stock','BRL','B3'),
('SEQL3','Sequoia Logistica ON','br_stock','BRL','B3'),
('SGPS3','Springs ON','br_stock','BRL','B3'),
('SIMH3','Simpar ON','br_stock','BRL','B3'),
('SOMA3','Grupo SOMA ON','br_stock','BRL','B3'),
('SQIA3','Sinqia ON','br_stock','BRL','B3'),
('SULA11','SulAmerica Unit','br_stock','BRL','B3'),
('TASA4','Taurus Armas PN','br_stock','BRL','B3'),
('TEND3','Tenda ON','br_stock','BRL','B3'),
('TGMA3','Tegma ON','br_stock','BRL','B3'),
('TRIS3','Trisul ON','br_stock','BRL','B3'),
('TTEN3','3Tentos ON','br_stock','BRL','B3'),
('TUPY3','Tupy ON','br_stock','BRL','B3'),
('UNIP6','Unipar PNB','br_stock','BRL','B3'),
('USIM3','Usiminas ON','br_stock','BRL','B3'),
('VLID3','Valid ON','br_stock','BRL','B3'),
('VULC3','Vulcabras ON','br_stock','BRL','B3'),
('WIZC3','Wiz Co ON','br_stock','BRL','B3'),
('ZAMP3','Zamp ON','br_stock','BRL','B3'),
('AERI3','Aeris ON','br_stock','BRL','B3'),
('ALPK3','Alpapark ON','br_stock','BRL','B3'),
('AMER3','Americanas ON','br_stock','BRL','B3'),
('AESB3','AES Brasil ON','br_stock','BRL','B3'),
('CGAS5','Comgas PNA','br_stock','BRL','B3'),
('CLSC4','Celesc PN','br_stock','BRL','B3'),
('GGBR3','Gerdau ON','br_stock','BRL','B3'),
('GOAU3','Metalurgica Gerdau ON','br_stock','BRL','B3'),
('LUPA3','Lupatech ON','br_stock','BRL','B3'),
('MDIA3','M.Dias Branco ON','br_stock','BRL','B3'),
('MERC4','Mercantil do Brasil PN','br_stock','BRL','B3'),
('MRSA6B','Minerva Supp PNB','br_stock','BRL','B3'),
('OIBR3','Oi ON','br_stock','BRL','B3'),
('PDGR3','PDG Realty ON','br_stock','BRL','B3'),
('PEAB3','Porto Alegre ON','br_stock','BRL','B3'),
('PINE4','Pine PN','br_stock','BRL','B3'),
('PRNR3','Priner ON','br_stock','BRL','B3'),
('PTNT4','Pettenati PN','br_stock','BRL','B3'),
('RCSL3','Recrusul ON','br_stock','BRL','B3'),
('SAPR3','Sanepar ON','br_stock','BRL','B3'),
('SCAR3','Sao Carlos ON','br_stock','BRL','B3'),
('SHUL4','Schulz PN','br_stock','BRL','B3'),
('SMLS3','Smiles ON','br_stock','BRL','B3'),
('TFCO4','Track & Field PN','br_stock','BRL','B3'),
('TPIS3','Triunfo ON','br_stock','BRL','B3'),
('VIVR3','Viver ON','br_stock','BRL','B3'),
('WLMM4','WLM PN','br_stock','BRL','B3')
ON CONFLICT (ticker) DO NOTHING;

-- US Stocks (S&P 500 + popular — additional to 005)
INSERT INTO public.invest_assets (ticker, name, asset_type, currency, exchange) VALUES
('ANET','Arista Networks','us_stock','USD','NYSE'),
('APP','AppLovin Corp','us_stock','USD','NASDAQ'),
('ASML','ASML Holding','us_stock','USD','NASDAQ'),
('BIDU','Baidu Inc','us_stock','USD','NASDAQ'),
('BILI','Bilibili Inc','us_stock','USD','NASDAQ'),
('CI','Cigna Group','us_stock','USD','NYSE'),
('CLX','Clorox Co','us_stock','USD','NYSE'),
('CME','CME Group','us_stock','USD','NASDAQ'),
('CPRT','Copart Inc','us_stock','USD','NASDAQ'),
('DASH','DoorDash Inc','us_stock','USD','NASDAQ'),
('DELL','Dell Technologies','us_stock','USD','NYSE'),
('DKNG','DraftKings Inc','us_stock','USD','NASDAQ'),
('DOCU','DocuSign Inc','us_stock','USD','NASDAQ'),
('EA','Electronic Arts','us_stock','USD','NASDAQ'),
('EL','Estee Lauder','us_stock','USD','NYSE'),
('ENPH','Enphase Energy','us_stock','USD','NASDAQ'),
('ESTC','Elastic NV','us_stock','USD','NYSE'),
('F','Ford Motor','us_stock','USD','NYSE'),
('FAST','Fastenal Co','us_stock','USD','NASDAQ'),
('FDX','FedEx Corp','us_stock','USD','NYSE'),
('FSLR','First Solar','us_stock','USD','NASDAQ'),
('GM','General Motors','us_stock','USD','NYSE'),
('GRAB','Grab Holdings','us_stock','USD','NASDAQ'),
('HPQ','HP Inc','us_stock','USD','NYSE'),
('ICE','Intercontinental Exchange','us_stock','USD','NYSE'),
('JD','JD.com Inc','us_stock','USD','NASDAQ'),
('KHC','Kraft Heinz','us_stock','USD','NASDAQ'),
('KVUE','Kenvue Inc','us_stock','USD','NYSE'),
('MARA','Marathon Digital','us_stock','USD','NASDAQ'),
('MELI','MercadoLibre Inc','us_stock','USD','NASDAQ'),
('MET','MetLife Inc','us_stock','USD','NYSE'),
('MNST','Monster Beverage','us_stock','USD','NASDAQ'),
('MRVL','Marvell Technology','us_stock','USD','NASDAQ'),
('MSI','Motorola Solutions','us_stock','USD','NYSE'),
('MU','Micron Technology','us_stock','USD','NASDAQ'),
('NIO','NIO Inc','us_stock','USD','NYSE'),
('NOC','Northrop Grumman','us_stock','USD','NYSE'),
('NU','Nu Holdings','us_stock','USD','NYSE'),
('ON','ON Semiconductor','us_stock','USD','NASDAQ'),
('ORLY','OReilly Automotive','us_stock','USD','NASDAQ'),
('PARA','Paramount Global','us_stock','USD','NASDAQ'),
('PINS','Pinterest Inc','us_stock','USD','NYSE'),
('RBLX','Roblox Corp','us_stock','USD','NYSE'),
('REGN','Regeneron Pharmaceuticals','us_stock','USD','NASDAQ'),
('RIVN','Rivian Automotive','us_stock','USD','NASDAQ'),
('ROKU','Roku Inc','us_stock','USD','NASDAQ'),
('SE','Sea Limited','us_stock','USD','NYSE'),
('SNAP','Snap Inc','us_stock','USD','NYSE'),
('SPOT','Spotify Technology','us_stock','USD','NYSE'),
('SYK','Stryker Corp','us_stock','USD','NYSE'),
('TFC','Truist Financial','us_stock','USD','NYSE'),
('TSM','Taiwan Semiconductor','us_stock','USD','NYSE'),
('TTWO','Take-Two Interactive','us_stock','USD','NASDAQ'),
('U','Unity Software','us_stock','USD','NYSE'),
('USB','US Bancorp','us_stock','USD','NYSE'),
('WDAY','Workday Inc','us_stock','USD','NASDAQ'),
('WBD','Warner Bros Discovery','us_stock','USD','NASDAQ'),
('XP','XP Inc','us_stock','USD','NASDAQ'),
('ZIM','ZIM Integrated Shipping','us_stock','USD','NYSE'),
('ZM','Zoom Video Communications','us_stock','USD','NASDAQ'),
('ZTO','ZTO Express','us_stock','USD','NYSE'),
('TEAM','Atlassian Corp','us_stock','USD','NASDAQ'),
('TTD','The Trade Desk','us_stock','USD','NASDAQ'),
('HUBS','HubSpot Inc','us_stock','USD','NYSE'),
('OKTA','Okta Inc','us_stock','USD','NASDAQ'),
('MDB','MongoDB Inc','us_stock','USD','NASDAQ'),
('TWLO','Twilio Inc','us_stock','USD','NYSE'),
('PATH','UiPath Inc','us_stock','USD','NYSE'),
('S','SentinelOne Inc','us_stock','USD','NYSE'),
('CELH','Celsius Holdings','us_stock','USD','NASDAQ'),
('SMCI','Super Micro Computer','us_stock','USD','NASDAQ'),
('VST','Vistra Corp','us_stock','USD','NYSE'),
('CEG','Constellation Energy','us_stock','USD','NASDAQ'),
('TJX','TJX Companies','us_stock','USD','NYSE'),
('ROST','Ross Stores','us_stock','USD','NASDAQ'),
('MAR','Marriott Intl','us_stock','USD','NASDAQ'),
('HLT','Hilton Worldwide','us_stock','USD','NYSE'),
('SYF','Synchrony Financial','us_stock','USD','NYSE'),
('ALLY','Ally Financial','us_stock','USD','NYSE'),
('PNC','PNC Financial','us_stock','USD','NYSE'),
('FITB','Fifth Third Bancorp','us_stock','USD','NASDAQ'),
('CFG','Citizens Financial','us_stock','USD','NYSE'),
('KEY','KeyCorp','us_stock','USD','NYSE'),
('HBAN','Huntington Bancshares','us_stock','USD','NASDAQ'),
('WBA','Walgreens Boots Alliance','us_stock','USD','NASDAQ'),
('CVS','CVS Health','us_stock','USD','NYSE'),
('HCA','HCA Healthcare','us_stock','USD','NYSE'),
('ELV','Elevance Health','us_stock','USD','NYSE'),
('CI','Cigna Group','us_stock','USD','NYSE'),
('MDT','Medtronic plc','us_stock','USD','NYSE'),
('EW','Edwards Lifesciences','us_stock','USD','NYSE'),
('BSX','Boston Scientific','us_stock','USD','NYSE'),
('ZBH','Zimmer Biomet','us_stock','USD','NYSE'),
('STE','STERIS plc','us_stock','USD','NYSE'),
('A','Agilent Technologies','us_stock','USD','NYSE'),
('WAT','Waters Corp','us_stock','USD','NYSE'),
('BIO','Bio-Rad Laboratories','us_stock','USD','NYSE'),
('ILMN','Illumina Inc','us_stock','USD','NASDAQ'),
('DXCM','DexCom Inc','us_stock','USD','NASDAQ'),
('ALGN','Align Technology','us_stock','USD','NASDAQ'),
('IDXX','IDEXX Laboratories','us_stock','USD','NASDAQ'),
('VEEV','Veeva Systems','us_stock','USD','NYSE'),
('ZTS','Zoetis Inc','us_stock','USD','NYSE')
ON CONFLICT (ticker) DO NOTHING;

-- US REITs (additional)
INSERT INTO public.invest_assets (ticker, name, asset_type, currency, exchange) VALUES
('SBAC','SBA Communications REIT','us_stock','USD','NASDAQ'),
('WPC','W. P. Carey REIT','us_stock','USD','NYSE'),
('GLPI','Gaming and Leisure Properties','us_stock','USD','NASDAQ'),
('CUBE','CubeSmart REIT','us_stock','USD','NYSE'),
('EXR','Extra Space Storage','us_stock','USD','NYSE'),
('LSI','Life Storage REIT','us_stock','USD','NYSE'),
('ESS','Essex Property Trust','us_stock','USD','NYSE'),
('UDR','UDR Inc REIT','us_stock','USD','NYSE'),
('CPT','Camden Property Trust','us_stock','USD','NYSE'),
('KIM','Kimco Realty','us_stock','USD','NYSE'),
('REG','Regency Centers','us_stock','USD','NASDAQ'),
('FRT','Federal Realty Investment','us_stock','USD','NYSE'),
('BXP','BXP Inc','us_stock','USD','NYSE'),
('SLG','SL Green Realty','us_stock','USD','NYSE'),
('MPW','Medical Properties Trust','us_stock','USD','NYSE'),
('OHI','Omega Healthcare','us_stock','USD','NYSE'),
('HR','Healthcare Realty Trust','us_stock','USD','NYSE'),
('DOC','Physicians Realty Trust','us_stock','USD','NYSE'),
('HIW','Highwoods Properties','us_stock','USD','NYSE'),
('KRC','Kilroy Realty','us_stock','USD','NYSE')
ON CONFLICT (ticker) DO NOTHING;

-- Fixed Income (additional types)
INSERT INTO public.invest_assets (ticker, name, asset_type, currency, exchange) VALUES
-- Debentures
('DEB-CDI','Debenture pos-fixado CDI','fixed_income','BRL','Renda Fixa'),
('DEB-IPCA','Debenture IPCA+','fixed_income','BRL','Renda Fixa'),
('DEB-PRE','Debenture prefixado','fixed_income','BRL','Renda Fixa'),
('DEB-INF-CDI','Debenture Incentivada CDI','fixed_income','BRL','Renda Fixa'),
('DEB-INF-IPCA','Debenture Incentivada IPCA+','fixed_income','BRL','Renda Fixa'),
-- LCI/LCA variants
('LCI-IPCA','LCI IPCA+','fixed_income','BRL','Renda Fixa'),
('LCA-IPCA','LCA IPCA+','fixed_income','BRL','Renda Fixa'),
-- CRI/CRA additional
('CRI-CDI','CRI CDI','fixed_income','BRL','Renda Fixa'),
('CRI-PRE','CRI prefixado','fixed_income','BRL','Renda Fixa'),
('CRA-IPCA','CRA IPCA+','fixed_income','BRL','Renda Fixa'),
('CRA-PRE','CRA prefixado','fixed_income','BRL','Renda Fixa'),
-- LC additional
('LC-IPCA','Letra de Cambio IPCA+','fixed_income','BRL','Renda Fixa'),
('LC-PRE','Letra de Cambio prefixado','fixed_income','BRL','Renda Fixa'),
-- CDB variants
('CDB-CDI-LIQ','CDB CDI liquidez diaria','fixed_income','BRL','Renda Fixa'),
-- Tesouro Direto additional
('TD-IPCA-JUROS','Tesouro IPCA+ com Juros Semestrais (NTN-B)','fixed_income','BRL','Renda Fixa'),
('TD-PRE-JUROS','Tesouro Prefixado com Juros Semestrais (NTN-F)','fixed_income','BRL','Renda Fixa'),
('TD-EDUCA','Tesouro RendA+ Educa','fixed_income','BRL','Renda Fixa'),
-- Poupanca
('POUP','Caderneta de Poupanca','fixed_income','BRL','Renda Fixa'),
-- Fundos RF
('FRF-DI','Fundo RF DI','fixed_income','BRL','Renda Fixa'),
('FRF-IPCA','Fundo RF IPCA','fixed_income','BRL','Renda Fixa'),
('FRF-CRED','Fundo RF Credito Privado','fixed_income','BRL','Renda Fixa')
ON CONFLICT (ticker) DO NOTHING;

-- Additional BDRs (missing from 006)
INSERT INTO public.invest_assets (ticker, name, asset_type, currency, exchange) VALUES
('AMD34','AMD BDR','br_bdr','BRL','B3'),
('ARMT34','Arm Holdings BDR','br_bdr','BRL','B3'),
('BABA34','Alibaba BDR','br_bdr','BRL','B3'),
('BINC34','Broadcom BDR','br_bdr','BRL','B3'),
('C1RM34','CRM Salesforce BDR','br_bdr','BRL','B3'),
('DDOG34','Datadog BDR','br_bdr','BRL','B3'),
('EQIX34','Equinix BDR','br_bdr','BRL','B3'),
('FCEL34','FuelCell Energy BDR','br_bdr','BRL','B3'),
('GILD34','Gilead Sciences BDR','br_bdr','BRL','B3'),
('HOOD34','Robinhood BDR','br_bdr','BRL','B3'),
('ISRG34','Intuitive Surgical BDR','br_bdr','BRL','B3'),
('MELI34','MercadoLibre BDR','br_bdr','BRL','B3'),
('NFLX34','Netflix BDR','br_bdr','BRL','B3'),
('N1VD34','Novo Nordisk BDR','br_bdr','BRL','B3'),
('PLTR34','Palantir BDR','br_bdr','BRL','B3'),
('PYPL34','PayPal BDR','br_bdr','BRL','B3'),
('QCOM34','Qualcomm BDR','br_bdr','BRL','B3'),
('SBUX34','Starbucks BDR','br_bdr','BRL','B3'),
('SNAP34','Snap BDR','br_bdr','BRL','B3'),
('SOFI34','SoFi Technologies BDR','br_bdr','BRL','B3'),
('TIKN34','TikTok ByteDance BDR','br_bdr','BRL','B3'),
('T1MU34','T-Mobile BDR','br_bdr','BRL','B3'),
('U1NH34','UnitedHealth BDR','br_bdr','BRL','B3'),
('X1OM34','ExxonMobil BDR','br_bdr','BRL','B3')
ON CONFLICT (ticker) DO NOTHING;

-- Additional ETFs BR (missing from 006)
INSERT INTO public.invest_assets (ticker, name, asset_type, currency, exchange) VALUES
('BOVA11','iShares Ibovespa ETF','br_etf','BRL','B3'),
('IVVB11','iShares S&P500 BRL ETF','br_etf','BRL','B3'),
('HASH11','Hashdex Nasdaq Crypto ETF','br_etf','BRL','B3'),
('TECK11','It Now NYSE FANG+ ETF','br_etf','BRL','B3'),
('NDIV11','Trend ETF IDIV','br_etf','BRL','B3'),
('SHOT11','ETF de Ações Small Caps','br_etf','BRL','B3'),
('GENB11','Trend ETF Genial BDRX','br_etf','BRL','B3'),
('JURO11','Trend ETF Juro Real','br_etf','BRL','B3'),
('CRPT11','Empiricus Trava Cripto ETF','br_etf','BRL','B3'),
('META11','It Now META ESG ETF','br_etf','BRL','B3'),
('ACWI11','Trend ETF MSCI ACWI','br_etf','BRL','B3'),
('5GTK11','Trend ETF 5G Tech','br_etf','BRL','B3'),
('ESGE11','It Now ISE ESG ETF','br_etf','BRL','B3'),
('USTK11','Trend ETF Nasdaq 100 Tech','br_etf','BRL','B3')
ON CONFLICT (ticker) DO NOTHING;

-- Additional Cryptocurrencies
INSERT INTO public.invest_assets (ticker, name, asset_type, currency, exchange, coingecko_id) VALUES
('HBAR','Hedera','crypto','USD','CoinGecko','hedera-hashgraph'),
('KAS','Kaspa','crypto','USD','CoinGecko','kaspa'),
('SEI','Sei','crypto','USD','CoinGecko','sei-network'),
('STX','Stacks','crypto','USD','CoinGecko','blockstack'),
('TAO','Bittensor','crypto','USD','CoinGecko','bittensor'),
('TIA','Celestia','crypto','USD','CoinGecko','celestia'),
('ALGO','Algorand','crypto','USD','CoinGecko','algorand'),
('GRT','The Graph','crypto','USD','CoinGecko','the-graph'),
('SAND','The Sandbox','crypto','USD','CoinGecko','the-sandbox'),
('MANA','Decentraland','crypto','USD','CoinGecko','decentraland'),
('AXS','Axie Infinity','crypto','USD','CoinGecko','axie-infinity'),
('IMX','Immutable X','crypto','USD','CoinGecko','immutable-x'),
('CRO','Cronos','crypto','USD','CoinGecko','crypto-com-chain'),
('EGLD','MultiversX','crypto','USD','CoinGecko','elrond-erd-2'),
('THETA','Theta Network','crypto','USD','CoinGecko','theta-token'),
('VET','VeChain','crypto','USD','CoinGecko','vechain'),
('IOTA','IOTA','crypto','USD','CoinGecko','iota'),
('XLM','Stellar','crypto','USD','CoinGecko','stellar'),
('EOS','EOS','crypto','USD','CoinGecko','eos'),
('XTZ','Tezos','crypto','USD','CoinGecko','tezos')
ON CONFLICT (ticker) DO NOTHING;
